### ISSUE TITLE
GHA's on forks

### ISSUE THREAD

**Issue by billy-doyle** [compat-fork/diagrams#4]
https://stackoverflow.com/a/73317424/9992341

@JelleZijlstra believe the above will fix

**Comment by JelleZijlstra** [comment]
I've stared at the settings for a while but I can't find it. The SO answer seems to be about private repositories, but this one isn't. I previously went to https://github.com/compat-fork/diagrams/actions and pushed some button to enable actions, but it's not helping.

**Comment by billy-doyle** [comment]
Did you see the comments about the org level perms?

![image](https://github.com/user-attachments/assets/ed8ff31b-9c3d-4e92-b67c-93acce47feac)

**Comment by JelleZijlstra** [comment]
Found the dumbest solution: renaming the yml file made it so the action ran.

And yes, I checked the org-level settings too, but that setting is again just about private repos.

**Comment by billy-doyle** [comment]
Aha nice
